# serverless.yml
 
service: serverless-flask
 
plugins:
  - serverless-python-requirements
  - serverless-wsgi
  - serverless-version-tracker
custom:
  wsgi:
    app: app.app
    packRequirements: false
  pythonRequirements:
    dockerizePip: non-linux
 
provider:
  name: aws
  runtime: python3.6
  stage: dev
  region: eu-central-1
 
functions:
  app:
    handler: wsgi.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'

